public class DocumentEmail {
  public Blob blobContent;
  public Boolean isTestMode;
  public String contentType;
  public String emailContent;
  public String emailSubject;
  public String fileName;
  public String fromAddress;
  public String toAddress;
  public String targetObjectId; // Id of the Contact, Lead or User to which the email will be sent for Standard SF Emails.
  public String emailTemplateId;
  public String whatId;
  public ContentVersion contentVersion;
}